project 'NimbusCatalog.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Nimbus' do
  pod 'Nimbus', :path => '../../'
end
